---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - env: TEST_SUITE=frontend # ember tests (tests dir)
    - env: TEST_SUITE=backend TEST_SCENARIO=1 # node tests (node_tests dir)
    - env: TEST_SUITE=backend TEST_SCENARIO=2 # node tests (node_tests dir)

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - if [ "$TEST_SUITE" = "backend" ]; then npm test; fi
  - if [ "$TEST_SUITE" = "frontend" ]; then ember test; fi
