---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-release
  - TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-beta
  - TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-canary
  - TEST_SUITE=backend # node tests (node_tests dir)

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - if [ "$TEST_SUITE" = "backend" ]; then npm test; fi
  - if [ "$TEST_SUITE" = "frontend" ]; then ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup; fi
